site_name: mosaico

repo_url: https://github.com/orgs/mosaico-matrix/repositories

nav:
  - Home: index.md
  - App: [
          mobile-app/index.md,
          mobile-app/shared-library.md,
          mobile-app/config-generator.md,
          mobile-app/implementation-details.md,
          ]
  - Credits: credits/index.md

theme:
    name: material
    palette:
      accent: indigo

plugins:
    - search
    - glightbox
 #   - md_in_html
    - with-pdf:
        author: marco.coppola3@studio.unibo.it (0001020433)
        cover: true
        back_cover: true
        cover_title: Mosaico
        cover_subtitle: Project report for the "LAM" course
        copyright: Alma Mater Studiorum Università di Bologna
        heading_shift: false

markdown_extensions:
  - pymdownx.blocks.html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
    
extra_css:
    - stylesheets/extra.css

    