site_name: mosaico

repo_url: https://github.com/orgs/mosaico-matrix/repositories

nav:
  - Home: index.md
  - App: [
          mobile-app/index.md,
          mobile-app/shared-library.md,
          mobile-app/config-generator.md,
          mobile-app/implementation-details.md,
          ]
  - Credits: credits/index.md

theme:
    name: material
    palette:
      accent: indigo

plugins:
    - search
    - glightbox
 #   - md_in_html
    - with-pdf:
        author: Marco Coppola (0001020433)
        copyright: ANY TEXT
        cover: true
#        back_cover: true
#        cover_title: TITLE TEXT
#        cover_subtitle: SUBTITLE TEXT
#        toc_title: TOC TITLE TEXT
#        heading_shift: false
#        toc_level: 3
#        ordered_chapter_level: 2
#        excludes_children:
#          - 'release-notes/:upgrading'
#          - 'release-notes/:changelog'
#
#        exclude_pages:
#          - 'bugs/'
#          - 'appendix/contribute/'
#        convert_iframe:
#          - src: IFRAME SRC
#            img: POSTER IMAGE URL
#            text: ALTERNATE TEXT
#          - src: ...
#        two_columns_level: 3
#
#        render_js: true
#        headless_chrome_path: headless-chromium
#
#        output_path: any-place/document.pdf
#        enabled_if_env: ENABLE_PDF_EXPORT
#
#        debug_html: true
#        show_anchors: true
#        verbose: true

markdown_extensions:
  - pymdownx.blocks.html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
    
extra_css:
    - stylesheets/extra.css

    