site_name: mosaico

repo_url: https://github.com/orgs/mosaico-matrix/repositories

nav:
  - Home: index.md
  - App: [mobile-app/index.md,
          mobile-app/implementation-details.md,
          mobile-app/shared-library.md]
  - Credits: credits/index.md

theme:
    name: material
    palette:
      accent: indigo

plugins:
    - search
    - glightbox
 #   - md_in_html
#    - with-pdf

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
    
extra_css:
    - stylesheets/extra.css

    